# Generated by Django 2.1.3 on 2018-11-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmodel',
            name='pic',
            field=models.FileField(default='static/media/default.jpg', upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='photo',
            field=models.FileField(blank=True, default='static/media/default.jpg', upload_to='static/media/'),
        ),
    ]
